name: Audit the go source

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.20
      id: go
    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/cprint ./cmd/cprint
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/logging ./cmd/logging
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/mvx ./cmd/mvx
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/path_clean ./cmd/path_clean
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/print_status ./cmd/print_status
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/today ./cmd/today
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/mdtoc ./cmd/mdtoc
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/achelper ./cmd/achelper
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/namegen ./cmd/namegen
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/invgen ./cmd/invgen

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...

    - name: Run tests
      run: go test -race -vet=off ./...
