name: Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Verify dependencies
      run: go mod verify

    - name: Build all binaries
      run: |
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/cprint ./cmd/cprint
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/logging ./cmd/logging
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/mvx ./cmd/mvx
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/path_clean ./cmd/path_clean
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/print_status ./cmd/print_status
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/today ./cmd/today
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/mdtoc ./cmd/mdtoc
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/achelper ./cmd/achelper
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/namegen ./cmd/namegen
        CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -v -o build/invgen ./cmd/invgen

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Run tests
      run: go test -race -vet=off -coverprofile=coverage.out ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v7
      with:
        files: ./coverage.out
        flags: unittests
        fail_ci_if_error: false
