# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build the go sources

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get Branch
      id: branch
      run: echo "git_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_BRANCH

    - name: Get Hash
      id: hash
      run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH

    - name: Check Branch
      run: echo "${{ env.branch }}"

    - name: Check Hash
      run: echo "${{ env.hash }}"

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.20
      id: go

    - name: Build
      run: |
        ./build.sh package

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: arcive packages
        path: |
          pkg

